<?php

return [
    '头套' => [
        ['Asymmetric design temperament unique internal buckle hood', '不对称设计 气质独特内扣头套'],
        ['Lateral s-type Liu Hai natural casual headgear', '侧分S型刘海 自然随性头套'],
        ['Elegant and charming headgear with side curls', '侧分卷发 优雅迷人头套'],
        ['Sexy elegant hoodie with side score', '侧分中发 性感优雅头套'],
        ['Vintage Curly Hair Sexy charming Hoodie', '复古卷发 性感妩媚头套'],
        ['Korean Bob Sweet Cute Hoodie', '韩式BOB 甜美可爱头套'],
        ['Korean fluffy curly hair personality modern headgear', '韩式蓬松卷发 个性摩登头套'],
        ['Wine red long straight hair fresh charm hoodie', '酒红长直发 清新魅力头套'],
        ['Air-flavored curly woman full Hoodie', '空气感卷发 女人味十足头套'],
        ['Feminine headgear in a three-dimensional sense', '立体感中发 女人味十足头套'],
        ['Qi Liu Hai curly celebrity temperament Hoodie', '齐刘海卷发 名媛气质头套'],
        ['Fashion gradient style avant-garde hoodie', '时尚渐变色 风格前卫头套'],
        ['Candy Color slices dyed three-dimensional full-sense headgear', '糖果色片染 立体感十足头套'],
        ['Gorgeous hair color display modern temperament headgear', '绚丽发色 尽显摩登气质头套'],
        ['Natural big wave fashion charm hoodie', '自然大波浪 时尚魅力头套'],
    ],
    '发块' => [
        ['Natural straight hair gentle quiet to real hair block', '自然直发 温婉恬静至真发块'],
        ['Qi Liu Hai curly hair romantic charm to real hair block', '齐刘海卷发 浪漫妩媚至真发块'],
        ['Side air long curly hair light natural to real hair block', '侧分空气长卷发 轻盈自然至真发块'],
    ],
    '配件' => [
        ['Side of Liu Hai natural Realistic Beauty series', '侧分刘海 自然逼真缀美系列'],
        ['Air Liu Hai Gentle Sweet Beauty series', '空气刘海 温柔甜美缀美系列'],
        ['Straight Hair Ponytail personality completely embellished beauty series', '直发马尾 个性十足缀美系列'],
        ['Fluffy ponytail refreshing and beautiful series', '蓬松马尾 清爽有型缀美系列'],
    ],
    '单品' => [
        ['Human Hair Wig Wash kit', '人发假发洗护套装'],
        ['Human mixing wig Washing kit', '人化掺和假发洗护套装'],
        ['Hooded Bracket', '头套支架'],
        ['Wig Net Hat', '假发网帽'],
        ['Cosmetic box three-piece set', '化妆箱三件套'],
        ['Butterfly Hair Card', '蝴蝶发卡'],
        ['Rainbow Hair Belt', '彩虹发带'],
        ['Sheepskin Hair Hoop', '羊皮发箍'],
        ['Standard Series False eyelashes', '标准系列假睫毛'],
        ['Cosmetic Mirror', '化妆镜'],
        ['Wigs dedicated Comb', '假发专用梳'],
    ],
];
